package mor.itas.domain.valueobject.tp;

public enum TpAuditReportStatus {
    DRAFT,
    SUBMITTED_FOR_TEAM_LEADER_REVIEW,
    TEAM_LEADER_APPROVED,
    SUBMITTED_FOR_PROCESS_OWNER_REVIEW,
    PROCESS_OWNER_APPROVED,
    SUBMITTED_FOR_FINAL_APPROVAL,
    FULLY_APPROVED,
    SENT_TO_TAXPAYER,
    TAXPAYER_SIGNED,
    TAXPAYER_OBJECTED,
    NO_RESPONSE_REFERRED
}
